version: '3'

services:
  postgres:
    image: postgres:15.0
    ports:
      - 5436:5432
    environment:
      POSTGRES_DB: mreleaser
      POSTGRES_USER: mreleaser
      POSTGRES_PASSWORD: mreleaser
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200

  markdown-to-epub:
    image: machinum/pandoc-rest-api:latest
    build: ./pandoc
    ports:
      - 5000:5000
    volumes:
      - ./pandoc/output:/app/output
    profiles:
      - donotstart